services:
  mongo:
    image: mongo

    volumes:
      - ./data/db:/data/db:rw


  website:
    image: website
    build: ./website

    depends_on:
      - mongo


  proxy:
    image: nginx

    ports:
      - 80:80
      - 443:443

    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/certs:/certs:ro

    depends_on:
      - website
